version: '3.8'

services:
  mongodb:
    image: mongo:6.0.2
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_ROOT_DATABASE: paw
    restart: always
    ports:
      - 27018:27017
    volumes:
      - ./data/db:/data/db
